### ISSUE TITLE
result stream close due to many entrys/values

### ISSUE THREAD

**Issue by JustNotMe** [wstrange/dartdap#13]
Our Active Directory has ~130 objects in a OU i want to search for, but it seems the stream can't handle so many results.
Adding more attributes to the search decreases the number of entrys the stream can handle.

```
Unhandled exception:
The null object does not have a getter 'length'.

NoSuchMethodError: method not found: 'length'
Receiver: null
Arguments: []
#0      ConnectionManager.connect.<connect_async_body>.<anonymous closure> (package:dartdap/src/dartdap/client/connection_manager.dart:308:11)
#1      _RootZone.runBinaryGuarded (dart:async/zone.dart:1150)
#2      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:353)
#3      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:370)
#4      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:270)
#5      _SinkTransformerStreamSubscription._addError (dart:async/stream_transformers.dart:81)
#6      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1138)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#10     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#11     _StreamController._add (dart:async/stream_controller.dart:635)
#12     _StreamController.add (dart:async/stream_controller.dart:581)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:1659)
#14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1138)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#17     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#18     _StreamController._add (dart:async/stream_controller.dart:635)
#19     _StreamController.add (dart:async/stream_controller.dart:581)
#20     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:952)
#21     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#22     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#23     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

It is possible to Change the filter, so i only search for memberof parts and can generate so a full list, but this is kind a burden.

**Comment by hoylen** [comment]
Which release of _dartdap_ are you using? What does your _pubspec.lock_ file say?

It looks more like a bug that should be fixed, rather than trying to make a query that produces smaller results.

Are you able to track down which line calls "length" on a variable which is null? Obviously, something unexpected has happened: it should not be null, or that code should not have been reached in that situation.

The error message mentions line 308 of _connection_manager.dart_, but I can't see any use of "length" in that file. But the stack trace can be deceptive. If the problem is reproducible, find out where it happens by using the debugger, turning on the logging, or crude-but-effective print statements.

**Comment by JustNotMe** [comment]
new Logger("ldap.control").level = Level.FINEST; Shows certificate warnings, disabling ssl results in 0 crashes and all results.
Disabling ssl will work, but isnt really secure...

Other logger Show no Errors.

So its not an error in SIZE, but in TIME?

```
2016-07-06 07:22:36.373727: ldap.connection: WARNING: Invalid Certificate: issuer=/DC=de/DC=**/CN=** subject=/CN=**
2016-07-06 07:22:36.385440: ldap.connection: WARNING: SSL Connection will proceed. Please fix the certificate
2016-07-06 07:22:36.391298: ldap.connection: WARNING: Invalid Certificate: issuer=/DC=de/DC=**/CN=** subject=/CN=**
2016-07-06 07:22:36.399105: ldap.connection: WARNING: SSL Connection will proceed. Please fix the certificate
2016-07-06 07:22:36.410823: ldap.connection: WARNING: Invalid Certificate: issuer=/DC=de/DC=**/CN=** subject=/CN=**
2016-07-06 07:22:36.417667: ldap.connection: WARNING: SSL Connection will proceed. Please fix the certificate
2016-07-06 07:22:36.423523: ldap.connection: WARNING: Invalid Certificate: issuer=/DC=de/DC=**/CN=** subject=/CN=**
2016-07-06 07:22:36.436097: ldap.connection: WARNING: SSL Connection will proceed. Please fix the certificate
2016-07-06 07:22:36.464048: ldap.send.ldap: FINE: Send LDAP message: Msg(id=2, op=BND_REQ,controls=null)
2016-07-06 07:22:36.478699: ldap.send.ldap: FINE: Send LDAP message: Msg(id=2, op=BND_REQ,controls=null)
2016-07-06 07:22:36.500180: ldap.recv.ldap: FINE: LDAP message received: Id=2 protocolOp=Seq[ASNInteger(0) OctetString() OctetString() ]
2016-07-06 07:22:36.514828: ldap.send.ldap: FINE: LDAP request serviced: Msg(id=2, op=BND_REQ,controls=null) (51 ms)
2016-07-06 07:22:36.527526: ldap.send.ldap: FINE: Send LDAP message: Msg(id=3, op=SRCH_REQ,controls=null)
2016-07-06 07:22:36.537653: ldap.recv.ldap: FINE: LDAP message received: Id=2 protocolOp=Seq[ASNInteger(0) OctetString() OctetString() ]
2016-07-06 07:22:36.543999: ldap.send.ldap: FINE: LDAP request serviced: Msg(id=2, op=BND_REQ,controls=null) (64 ms)
```

**Comment by hoylen** [comment]
The certificate warnings are similar to what you get when you visit a Web site in a browser, and the domain name in the server certificate does not match the domain name in the URL being visited. It looks like the server certificate that Active Directory uses doesn't contain Internet style domain names, but uses X.400 style Distinguished Names (/DC=...). So I wouldn't worry about those warnings (though I think a future release of _dartdap_ should reject it by default, rather than insecurely accept them by default: the safer default).

It is surprising that it fails with SSL, but works without it. From what I can tell, the only difference between the two is the Dart `Socket` that is opened. All the high-level code is the same. Maybe it is a buffering issue which changes when SSL is used: the actual bytes being transported is exactly the same. Is that what you mean by "time"?

The logging probably won't detect an error, but might provide clues. Are you able to turn on all logging to `Level.FINEST` or `Level.ALL` and look at what happens immediately _before_ the null exception is thrown?

**Comment by JustNotMe** [comment]
AD Server: Windows 2012R2
dev host: Windows 10 x64

Dart: 1.17
dartdap: .0.1.0-Alpha

Still no signs of errors...

last entry:

```
ldap.recv.ldap: FINER: LDAP response received: SRCH_RES_ENTRY
ldap.recv.ldap: FINE: Search Result Entry: dn=CN=**,OU=**,OU=**,DC=**,DC=**
ldap.recv.ldap: FINEST: attribute: sAMAccountName={**}
```

ssems like a clean cut..

**Comment by JustNotMe** [comment]
```
Unhandled exception:
The null object does not have a getter 'length'.

NoSuchMethodError: method not found: 'length'
Receiver: null
Arguments: []
#0      ConnectionManager.connect.<connect_async_body>.<anonymous closure> (**package:dartdap/src/dartdap/client/connection_manager.dart:308:11**)
#1      _RootZone.runBinaryGuarded (dart:async/zone.dart:1150)
```

```
_socket
          .transform(_createLdapTransformer())
          .listen((m) => _handleLDAPMessage(m), onError: (error, stacktrace) {
        loggerConnection.finer("Socket error", error, stacktrace);
        if (error is SocketException) {
          throw new LdapSocketException(error);
        } else {
          print(**stacktrace**);
          print("______________________________________");
          throw error;
        }
      });
```

```
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      _createLdapTransformer.<anonymous closure> (**package:dartdap/src/dartdap/client/ldap_transformer.dart:26:56**)
#3      _HandlerEventSink.add (dart:async/stream_transformers.dart:217)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:119)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1138)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#8      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#9      _StreamController._add (dart:async/stream_controller.dart:635)
#10     _StreamController.add (dart:async/stream_controller.dart:581)
#11     _Socket._onData (dart:io-patch/socket_patch.dart:1659)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1138)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#15     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#16     _StreamController._add (dart:async/stream_controller.dart:635)
#17     _StreamController.add (dart:async/stream_controller.dart:581)
#18     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:952)
#19     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#20     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#21     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

dont know if it helps, but might be an socket error O_o

can't investigate further, not good enough and i got confussed over your Code >_<'

**Comment by wstrange** [comment]
Are there any corresponding errors on the AD side that might give us further clues? i.e. Does AD not like something in the request, etc.

**Comment by JustNotMe** [comment]
Can't find anything related in the serverlogs.

**Comment by hoylen** [comment]
Warren,

> dartdap: .0.1.0-Alpha

That looks like the latest code on GitHub, that has not been released as a package. The most recent published package is version 0.0.9. But that's fine.

```
    _socket
      .transform(_createLdapTransformer())
      .listen((m) => _handleLDAPMessage(m), onError: (error, stacktrace) {
    loggerConnection.finer("Socket error", error, stack trace); // this is line 304
    if (error is SocketException) {
      throw new LdapSocketException(error);
    } else {
      throw error; // this is line 308
    }
```

Line 308 in _connection_manger.dart_ is the _onError_ method for the `listen` method. The listen method on the stream of LDAP messages. So I suspect the problem is somewhere in the `StreamTransformer` that converts bytes to LDAP messages, because that's got many calls to "length".

But it does seem strange that the "Socket error" FINER log message from line 304 didn't get printed out. _JustNotMe_: did you set the logging level on the Logger for "ldap.connection" with something like:

```
new Logger("ldap.connection").level = Level.ALL;
```

There is not enough logging to identify exactly where the problem is. In normal operation, we expect to see log messages with "ldap.recv.ldap: FINEST: attribute: ..." from processing one search result entry and then immediately "ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: ..." for the next result entry. So the current log entries don't really tell us much, other than:
- there probably were bytes left over to parse (otherwise we would have seen "ldap.recv.bytes: FINE: Bytes received:..." for extra bytes received from the socket's byte stream); and
- the parsing did not get as far as identifying the next ASN.1 object.

I could add some "FINEST" level logging to the _StreamTransformer_ and see if that tells us anything more. Unfortunately, we can't reproduce the problem, so will have to depend on _JustNotMe_ to run it... but that should be easy, since he/she is already running off the version on GitHub rather than a pub package release.

**Comment by JustNotMe** [comment]
Logging on _ldap.connection_ wasn't on your example code on pub.dartlang, so i havent set it.

Setting it only shows

```
ldap.connection: FINER: Opening secure socket to 192.168.4.18:636
ldap.connection: WARNING: Invalid Certificate: issuer=/DC=de/DC=** /CN=**  subject=/CN=** 
ldap.connection: WARNING: SSL Connection will proceed. Please fix the certificate
ldap.connection: WARNING: Invalid Certificate: issuer=/DC=de/DC=** /CN=**  subject=/CN=** ldap.connection: WARNING: SSL Connection will proceed. Please fix the certificate
ldap.connection: FINE: Opened secure socket to 192.168.4.18:636
ldap.send.ldap: FINE: Send LDAP message: Msg(id=2, op=BND_REQ,controls=null)
ldap.recv.bytes: FINE: Bytes received: 22
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 22
ldap.recv.asn1: FINE: ASN.1 object received: tag=48, length=16
ldap.recv.asn1: FINEST: ASN.1 value: [2, 1, 2, 97, 132, 0, 0, 0, 7, 10, 1, 0, 4, 0, 4, 0]
ldap.recv.ldap: FINE: LDAP message received: Id=2 protocolOp=Seq[ASNInteger(0) OctetString() OctetString() ]
ldap.recv.ldap: FINER: LDAP response received: BND_RESP
ldap.recv.ldap: FINER: Response op=Msg(id=2, op=BND_RESP,controls=null)
ldap.recv.ldap: FINER: Parse LDAP result: Seq[ASNInteger(0) OctetString() OctetString() ]
ldap.send.ldap: FINE: LDAP request serviced: Msg(id=2, op=BND_REQ,controls=null) (62 ms)
ldap.send.ldap: FINE: Send LDAP message: Msg(id=3, op=SRCH_REQ,controls=null)
ldap.connection: FINER: close() waiting for queue to drain pendingResponse={3: PendingOp m=Msg(id=3, op=SRCH_REQ,controls=null)}
ldap.recv.bytes: FINE: Bytes received: 8191
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 121
ldap.recv.asn1: FINE: ASN.1 object received: tag=48, length=115
ldap.recv.asn1: FINEST: ASN.1 value: [2, 1, 3, 100, 132, 0, 0, 0, 104, 4, 61, 67, 78, 61, 83, 116, 101, 118, 101, 32, 69, 108, 108, 101, 114, 44, 79, 85, 61, 77, 105, 116, 97, 114, 98, 101, 105, 116, 101, 114, 44, 79, 85, 61, 95, 66, 101, 110, 117, 116, 122, 101, 114, 44, 68, 67, 61, 105, 110, 110, 111, 118, 97, 100, 111, 109, 44, 68, 67, 61, 100, 101, 48, 132, 0, 0, 0, 35, 48, 132, 0, 0, 0, 29, 4, 14, 115, 65, 77, 65, 99, 99, 111, 117, 110, 116, 78, 97, 109, 101, 49, 132, 0, 0, 0, 7, 4, 5, 69, 108, 108, 101, 114, 48, 132]
ldap.recv.ldap: FINE: LDAP message received: Id=3 protocolOp=Seq[OctetString(CN=** ,OU=** ,OU=** ,DC=** ,DC=** ) Seq[Seq[OctetString(sAMAccountName) Set[OctetString(** ) ] ] ] ]
ldap.recv.ldap: FINER: LDAP response received: SRCH_RES_ENTRY
ldap.recv.ldap: FINE: Search Result Entry: dn=CN=** ,OU=** ,OU** ,DC=** ,DC=** 
ldap.recv.ldap: FINEST: attribute: sAMAccountName={** }

...
many other results...
...

ldap.connection: FINER: close() waiting for queue to drain pendingResponse={3: PendingOp m=Msg(id=3, op=SRCH_REQ,controls=null)}
ldap.connection: FINER: Socket error
```

That it is an socket error >.>

Parsing seems Ok, it just stops.

added a Test on Linux: 

```
Linux ghost-srv 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
Dart VM version: 1.17.1 (Fri Jun 10 04:55:46 2016) on "linux_x64"
```

= same result

EDIT:
Changed to ssl: false

```
ldap.connection: FINER: Opening socket to 192.168.4.18:389
ldap.connection: FINE: Opened socket to 192.168.4.18:389
ldap.send.ldap: FINE: Send LDAP message: Msg(id=2, op=BND_REQ,controls=null)
ldap.recv.bytes: FINE: Bytes received: 22
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 22
ldap.recv.asn1: FINE: ASN.1 object received: tag=48, length=16
ldap.recv.asn1: FINEST: ASN.1 value: [2, 1, 2, 97, 132, 0, 0, 0, 7, 10, 1, 0, 4, 0, 4, 0]
ldap.recv.ldap: FINE: LDAP message received: Id=2 protocolOp=Seq[ASNInteger(0) OctetString() OctetString() ]
ldap.recv.ldap: FINER: LDAP response received: BND_RESP
ldap.recv.ldap: FINER: Response op=Msg(id=2, op=BND_RESP,controls=null)
ldap.recv.ldap: FINER: Parse LDAP result: Seq[ASNInteger(0) OctetString() OctetString() ]
ldap.send.ldap: FINE: LDAP request serviced: Msg(id=2, op=BND_REQ,controls=null) (62 ms)
ldap.send.ldap: FINE: Send LDAP message: Msg(id=3, op=SRCH_REQ,controls=null)
ldap.connection: FINER: close() waiting for queue to drain pendingResponse={3: PendingOp m=Msg(id=3, op=SRCH_REQ,controls=null)}
ldap.recv.bytes: FINE: Bytes received: 10927
```

take a closer look on the **ldap.recv.bytes: FINE: Bytes received: 10927**

in ssl mode it stops by 8191 Bytes:

adding more Attributes to attr: = still 8191 Bytes in ssl mode.

So its seems the ssl socket can only read 8MBytes?

**Comment by hoylen** [comment]
Thanks for the logging on _ldap.connection_. I see what is going on.

**The evidence**

Here's a subset of those log entries:
1. ldap.connection: FINE: Opened secure socket to 192.168.4.18:636
2. ldap.send.ldap: FINE: Send LDAP message: Msg(id=2, op=BND_REQ,controls=null)
3. ldap.recv.bytes: FINE: Bytes received: 22
4. ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 22
5. ldap.recv.ldap: FINER: LDAP response received: BND_RESP
6. ldap.send.ldap: FINE: Send LDAP message: Msg(id=3, op=SRCH_REQ,controls=null)
7. ldap.connection: FINER: close() waiting for queue to drain pendingResponse={3: PendingOp m=Msg(id=3, op=SRCH_REQ,controls=null)}
8. ldap.recv.bytes: FINE: Bytes received: 8191
9. ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 121
10. ldap.connection: FINER: close() waiting for queue to drain pendingResponse={3: PendingOp m=Msg(id=3, op=SRCH_REQ,controls=null)}
11. ldap.connection: FINER: Socket error

Here's what is happening:
1. A connection is made (1).
2. A bind request is sent (2).
3. The bind response is received and processed (2-5).
4. A search request is sent (6).
5. A call to `close` is made, but since the search has not finished, it is still on the queue of pending requests. Hence, the _close_ operation is going to wait until the queue is empty before really closing (7).
6. The first 8191 bytes of the search response is received (8).
7. The first 121 bytes is parsed into an entry and processed (9).
8. Another call to `close` is made. The queue is still not empty, hence the message in (10).
9. An exception is thrown.

**The cause**

There are two potential causes here...

Firstly, **close is being called twice** on the _LDAPconnection_ object. Perhaps something has been nulled out as the connection is being closed, and the code never expected a (partially or completely) closed connection to be closed a second time.

Can you please check your code and see how that could happen (the _Navigate_ > _Declaration_ menu item in _WebStorm_ is very handy for this).

Note that _close_ returns a _Future_, so it could be a good idea to _await_ on it before proceeding on to doing other things. We probably should add code to properly handle such situations, but for the time being just avoid calling _close_ more than once.

Secondly, your code is calling _close_ **before the search has finished** getting and processing all the results. Although the code should handle this situation, there is no unit test for this piece of code so the problem might be in there too. For your own sanity you should _await for_ the stream of search results to finish before closing the connection: that way things happen in the proper order.

**The solution**

So it is safest to only call _close_ once and to do it after the _search_ operation has finished. Use _await_ and _await for_ like this:

```
var ldap = new LDAPConnection(...);
await ldap.connect();
await ldap.bind(...);
await for (SearchEntry entry in ldap.search(testDN.dn, filter, searchAttrs).stream) {
  print("Entry found");
}
await ldap.close();
```

**The size is not important**

I'm not worried about the 8191 bytes being less than what you get without SSL. That is probably due to the size of a buffer in the SSL/TLS code that gets flushed when it is full. The rest of the bytes would have arrived in the next chunk on the byte stream... if the program did not crash.

**Comment by wstrange** [comment]
Hoylen - brilliant.  Async code is so much fun :-)

**Comment by JustNotMe** [comment]
Im not calling Close() twice, don't know why i have pasted it so.

commenting Close out, does nothing. still 8191 Bytes and crashes.

```
ldap.connection: FINER: Opening secure socket to 192.168.4.18:636
ldap.connection: WARNING: Invalid Certificate: issuer=/DC=de/DC=**/CN=** subject=/CN=**
ldap.connection: WARNING: SSL Connection will proceed. Please fix the certificate
ldap.connection: WARNING: Invalid Certificate: issuer=/DC=de/DC=*/CN=** subject=/CN=**
ldap.connection: WARNING: SSL Connection will proceed. Please fix the certificate
ldap.connection: FINE: Opened secure socket to 192.168.4.18:636
ldap.send.ldap: FINE: Send LDAP message: Msg(id=2, op=BND_REQ,controls=null)
ldap.recv.bytes: FINE: Bytes received: 22
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 22
ldap.send.ldap: FINE: LDAP request serviced: Msg(id=2, op=BND_REQ,controls=null) (43 ms)
ldap.send.ldap: FINE: Send LDAP message: Msg(id=3, op=SRCH_REQ,controls=null)
ldap.connection: FINER: close() waiting for queue to drain pendingResponse={3: PendingOp m=Msg(id=3, op=SRCH_REQ,controls=null)}
ldap.recv.bytes: FINE: Bytes received: 8191
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 173
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 191
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 177
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 175
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 183
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 189
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 171
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 173
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 175
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 185
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 193
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 177
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 185
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 179
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 191
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 183
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 187
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 177
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 185
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 185
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 179
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 179
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 201
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 175
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 185
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 177
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 189
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 169
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 171
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 185
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 189
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 177
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 183
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 181
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 185
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 187
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 199
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 177
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 173
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 185
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 175
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 177
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 189
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 181
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 181
ldap.connection: FINER: Socket error
Unhandled exception:
The null object does not have a getter 'length'.

NoSuchMethodError: method not found: 'length'
Receiver: null
Arguments: []
#0      ConnectionManager.connect.<connect_async_body>.<anonymous closure> (package:dartdap/src/dartdap/client/connection_manager.dart:309:11)
#1      _RootZone.runBinaryGuarded (dart:async/zone.dart:1150)
#2      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:353)
#3      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:370)
#4      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:270)
#5      _SinkTransformerStreamSubscription._addError (dart:async/stream_transformers.dart:81)
#6      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1138)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#10     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#11     _StreamController._add (dart:async/stream_controller.dart:635)
#12     _StreamController.add (dart:async/stream_controller.dart:581)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:1659)
#14     _RootZone.runUnaryGuarded (dart:async/zone.dart:1138)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
#17     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#18     _StreamController._add (dart:async/stream_controller.dart:635)
#19     _StreamController.add (dart:async/stream_controller.dart:581)
#20     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:952)
#21     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#22     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#23     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

ssl: false
var attrs = ["sAMAccountName", "sn", "name", "mail", "wwwHomepage"];

```
ldap.connection: FINER: Opening socket to 192.168.4.18:389
ldap.connection: FINE: Opened socket to 192.168.4.18:389
ldap.send.ldap: FINE: Send LDAP message: Msg(id=2, op=BND_REQ,controls=null)
ldap.recv.bytes: FINE: Bytes received: 22
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 22
ldap.send.ldap: FINE: LDAP request serviced: Msg(id=2, op=BND_REQ,controls=null) (46 ms)
ldap.send.ldap: FINE: Send LDAP message: Msg(id=3, op=SRCH_REQ,controls=null)
ldap.connection: FINER: close() waiting for queue to drain pendingResponse={3: PendingOp m=Msg(id=3, op=SRCH_REQ,controls=null)}
ldap.recv.bytes: FINE: Bytes received: 29228
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 324
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 344
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 330
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 324
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 330
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 346
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 320
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 324
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 287
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 342
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 352
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 330
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 340
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 332
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 348
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 338
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 344
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 328
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 340
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 340
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 332
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 332
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 364
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 326
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 340
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 330
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 346
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 318
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 322
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 346
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 346
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 328
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 340
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 332
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 340
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 344
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 362
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 330
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 324
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 342
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 328
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 328
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 346
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 334
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 336
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 294
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 318
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 342
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 370
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 346
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 340
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 340
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 354
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 326
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 313
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 348
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 338
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 338
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 358
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 292
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 320
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 324
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 354
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 324
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 350
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 338
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 324
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 368
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 350
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 282
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 345
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 332
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 342
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 334
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 296
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 300
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 291
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 287
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 283
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 340
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 342
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 348
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 330
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 281
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 338
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 334
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 331
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 322
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 22
ldap.send.ldap: FINE: LDAP request serviced: Msg(id=3, op=SRCH_REQ,controls=null) (692 ms)
ldap.connection: FINE: Closing socket
```

Code is unchanged, only ssl toggle.

**Comment by hoylen** [comment]
Ok, so _close_ is not being called twice.

But the most obvious difference between the with-SSL and the without SSL run is the size of each search response message is significantly different. The SSL ones are about 180 bytes in size, but the non-SSL ones are about 300 bytes: exact same search query and filter, right? That is very strange, since it should be the same results coming back.

Can you try running my clone and "parser-logging" branch, in which I've added more logging code. Put this in your _pubspec.yaml_ file:

```
dependencies:
  dartdap:
    git:
      url: https://github.com/hoylen/dartdap.git
      ref: parser-logging
```

That should work, according to
https://www.dartlang.org/tools/pub/dependencies.html#git-packages

Instructions for using it are here: https://github.com/wstrange/dartdap/pull/14

The extra logging will print out the bytes being received, so we should see why the two message sizes are so different.

**Comment by hoylen** [comment]
I suggest you email me the output hoylen@hoylen.com, instead of putting it into the GitHub issue... since it probably contains real data returned from your AD. Not to mention it will be big.

**Comment by JustNotMe** [comment]
the difference came from the change after turning off ssl and increase the attributes, size of each resp in ssl mode are ok.

Updated pubspec. and attr for ssl call:

Again only 8191 Bytes. the last entry shows that it is not enough data left to parse a object . 

```
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 340
ldap.recv.bytes: FINEST: remaining to parse: 1868
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 340
ldap.recv.bytes: FINEST: remaining to parse: 1528
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 332
ldap.recv.bytes: FINEST: remaining to parse: 1196
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 332
ldap.recv.bytes: FINEST: remaining to parse: 864
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 364
ldap.recv.bytes: FINEST: remaining to parse: 500
ldap.recv.bytes: FINER: Bytes parsed for ASN.1 object: 326
ldap.recv.bytes: FINEST: remaining to parse: 174
ldap.recv.bytes: FINEST: wait for more, leftover: {leftover.length} bytes

sometimes this entry is logged too, not always.
ldap.connection: FINER: close() waiting for queue to drain pendingResponse={3: PendingOp m=Msg(id=3, op=SRCH_REQ,controls=null)}

ldap.connection: FINER: Socket error
Unhandled exception:
The null object does not have a getter 'length'.

NoSuchMethodError: method not found: 'length'
Receiver: null
Arguments: []
```

**Comment by hoylen** [comment]
Perfect! I think I've found the bug.

Please run `pub update` to get the fix, which I've committed to that "parser-logging" branch of my clone.

**Comment by JustNotMe** [comment]
Its working now!
The 8191 Bytes are still present, but now you are just reconnecting after each chunk? Logging shows a close() after each chunk.

**Comment by hoylen** [comment]
That's great. The bug was a logging statement that was in the wrong spot: after when the variable was processed and then set to null. I've now moved the logging statement to earlier in the method.

Yes, the bytes arrive in chunks, when the socket has data to pass to the application. No, the application does not "reconnect" after each chunk, it just sits there waiting for the stream to call it (i.e. for the stream to give it chunks): bytes are pushed from the socket to the application, rather than the application pulling bytes from the socket. Yes, it comes in chunks. The SSL layer changes when they bytes are ready, which is why they are chunked up differently from when SSL is not used.

The log messages for "close" are actually log messages of it checking if the queue is empty so it can finally perform the close it was asked to do. In this case, it is not yet ready (i.e. the search has not finished) until the last chunk is received.

**Warren**: I'll re-submit a pull request for this fix and (once it has been pulled in) then publish a new version 0.0.10 release package.

**JustNotMe**: once that is done, I would strongly recommend putting a dependency for version "^0.0.10" in your _pubspec.yaml_ file, instead of on the latest version in the Github repository. The next release (version 0.1.0) is planned to be a **breaking change** that will require you to make some changes to your code. By using the "^", _pub_ will not pull in that breaking change, until you are ready to move to that new release.

**Comment by JustNotMe** [comment]
Thanks for your efforts @all;

oh ok, misleading read of the Close() message.

i was planning to do so, after Pub.dartlang has the async version of dartdap, because it was less work to integrate :)

Is there a plan for a simple Login check? i plan to use it for auth user against our Domain. for now i use the bind() method for auth, if it Fails the Login will also fail.
But the user have to type there CN instead of der sAMAccountName, which can differ dependent on der admin who created the use >.<'

And sorry for my bad school english :/

**Comment by hoylen** [comment]
I'll let you know when the 0.0.10 package has been published on pub.dartlang.org.

I'm not sure what you mean by the "async version of dartdap", unless you simply mean the new documentation that has examples using async/await instead of the old documentation that used the "then" methods to deal with Futures. It is mostly the same, since async/await is really syntactic sugar for dealing with Futures: you can still use async/await with the older versions.

I also don't know what a "simple login check" is and I'm not familiar with Microsoft Active Directory, so don't know anything about _sAMAccountName_. Warren, do you?

**Comment by JustNotMe** [comment]
Dartdap 0.0.9 is async, but in 0.1.0 the Syntax and methods changed and it was a bit easier for me to use the Code :/

My goal is to auth a user against a MS ActiveDirectory using his domain loginName and password.
Currently i use his CN and Password with bind() to prove his identity and Password correctness

**Comment by hoylen** [comment]
The **dartdap 0.0.10** package has now been published on [pub.dartlang.org](https://pub.dartlang.org/packages/dartdap).

It has the fix to make it work with SSL and Active Directory.

Note: the arguments to the `LDAPConnection` constructor and its `bind` method has changed slightly, so any existing code will need to be updated.

**Comment by hoylen** [comment]
Correction, use **version 0.0.11**, in which `LDAPConnection` should be backward compatible.

Decided to put in extra work to undo some of the changes, so users coming from version 0.0.9 do not have to update their code.

**Comment by hoylen** [comment]
Further correction: **please use version 0.1.0**.

Although the methods are the same, the exceptions they throw are different which means this **is a breaking change** from version 0.0.9. Change your _pubspec.yaml_ accordingly, to pick up the version you want to use (i.e. "<=0.0.9" or "^0.1.0").

Forget version 0.0.10 and version 0.0.11 ever existed (I've asked for them to be removed from pub.dartlang.org). Sorry for this.

**Comment by hoylen** [comment]
There is now a **version 0.0.12** release of [dartdap](https://pub.dartlang.org/packages/dartdap) published. It is **fully backward compatible** with version 0.0.9: it has the bug fix, but no changes to exceptions that can be thrown).

If your _pubspec.yaml_ file had a dependency like:

```
dartdap: "^0.0.9"
```

Then it will do the right thing and use 0.0.12 (or any future non-breaking versions).

Sorry about all this.
