### ISSUE TITLE
FormatException when parsing non-UTF8 ASN.1 Octet Strings

### ISSUE THREAD

**Issue by ibims270** [wstrange/dartdap#69]
When performing a search that returns binary attributes (e.g. jpegPhoto, objectSID, userCertificate, etc.), dartdap throws a FormatException during ASN.1 decoding.

This happens because ASN1OctetString.utf8StringValue in asn1lib tries to decode all octet strings as UTF-8 — even if the contents are not valid UTF-8.

```
FormatException: Invalid UTF-8 byte (at offset 0)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1855:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351:37)
#2      Utf8Codec.decode (dart:convert/utf.dart:64:20)
#3      ASN1OctetString.utf8StringValue (package:asn1lib/src/asn1octetstring.dart:58:38)
#4      ASN1OctetString.toString (package:asn1lib/src/asn1octetstring.dart:73:24)
#5      ASN1Set.toString (package:asn1lib/src/asn1set.dart:75:17)
#6      ASN1Sequence.toString (package:asn1lib/src/asn1sequence.dart:81:17)
#7      ASN1Sequence.toString (package:asn1lib/src/asn1sequence.dart:81:17)
#8      ASN1Sequence.toString (package:asn1lib/src/asn1sequence.dart:81:17)
#9      _StringBase._interpolate (dart:core-patch/string_patch.dart:915:19)
#10     new LDAPMessage.fromBytes.<anonymous closure> (package:dartdap/src/protocol/ldap_message.dart:107:76)
#11     Logger.log (package:logging/src/logger.dart:214:50)
#12     Logger.fine (package:logging/src/logger.dart:268:7)
#13     new LDAPMessage.fromBytes (package:dartdap/src/protocol/ldap_message.dart:106:20)
#14     createLdapTransformer.<anonymous closure> (package:dartdap/src/client/ldap_transformer.dart:93:31)
#15     _HandlerEventSink.add (dart:async/stream_transformers.dart:230:17)
#16     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:115:24)
#17     _RootZone.runUnaryGuarded (dart:async/zone.dart:1778:10)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:381:11)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:312:7)
#20     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:798:19)
#21     _StreamController._add (dart:async/stream_controller.dart:663:7)
#22     _StreamController.add (dart:async/stream_controller.dart:618:5)
#23     _Socket._onData (dart:io-patch/socket_patch.dart:2904:41)
#24     _RootZone.runUnaryGuarded (dart:async/zone.dart:1778:10)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:381:11)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:312:7)
#27     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:798:19)
#28     _StreamController._add (dart:async/stream_controller.dart:663:7)
#29     _StreamController.add (dart:async/stream_controller.dart:618:5)
#30     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:2323:31)
#31     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1646:14)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```
**Expected behavior:**
Binary values should not be decoded as UTF-8 unless explicitly requested. The library should either:
Provide a safe fallback if decoding fails, or
Avoid decoding ASN.1 octet strings unless the value is known to be a UTF-8 string, or
Allow users to handle raw bytes before any decoding takes place.

**Steps to reproduce:**
Perform an LDAP search that includes binary attributes like jpegPhoto or objectSID.
Observe the crash when decoding the response.

**Suggested workaround:** 
Avoid this line in the current implementation in ldap_message.dart:106:
```
    loggerRecvLdap.fine(
        () => 'LDAP message received: Id=$messageId protocolOp=$protocolOp');
```
Either remove it or refactor it to not decode binary values using UTF-8 by default. The decoding should be deferred to the application layer, where it can be decided based on attribute type.

**Environment:**
dartdap version: 0.11.0
Dart SDK: 3.7.2
Flutter: 3.29.2
Platform: Linux

**Comment by wstrange** [comment]
Thanks for the detailed bug report. 

I pushed 0.11.1, which returns attributes as a Map<String,Set<Attribute>>  instead of a map of string values. 

I'm not sure if this is going to fix the binary data issue - I could probably use a test that creates and queries a jpegphoto.

I did a quick workaround on your suggestion to not log the protocoOp (which triggers the binary utf-8 error). 

```dart
    loggerRecvLdap.fine(
        () => 'LDAP message received: Id=$messageId');
```

This probably needs  more thought / work - but can you let me know if this gets you further


Thanks

**Comment by ibims270** [comment]
Many thanks for the quick reply and the 0.11.1 patch.


Unfortunately, the fix doesn’t resolve my issue. Now it crashes elsewhere with the following error:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: FormatException: Invalid UTF-8 byte (at offset 0)
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1855:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351:37)
#2      Utf8Codec.decode (dart:convert/utf.dart:64:20)
#3      ASN1OctetString.utf8StringValue (package:asn1lib/src/asn1octetstring.dart:58:38)
#4      ASN1OctetString.toString (package:asn1lib/src/asn1octetstring.dart:73:24)
#5      StringBuffer.write (dart:core-patch/string_buffer_patch.dart:71:22)
#6      StringBuffer.writeAll (dart:core-patch/string_buffer_patch.dart:108:7)
#7      Iterable.iterableToFullString (dart:core/iterable.dart:886:14)
#8      SetBase.setToString (dart:collection/set.dart:301:20)
#9      SetBase.toString (dart:collection/set.dart:132:24)
#10     _StringBase._interpolate (dart:core-patch/string_patch.dart:915:19)
#11     new SearchResultEntry (package:dartdap/src/protocol/search_result_entry.dart:48:73)
#12     ResponseHandler.handleResponse (package:dartdap/src/protocol/response_handler.dart:16:16)
#13     ConnectionManager._handleLDAPMessage (package:dartdap/src/client/connection_manager.dart:240:31)
#14     ConnectionManager.connect.<anonymous closure> (package:dartdap/src/client/connection_manager.dart:198:20)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1778:10)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:381:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:312:7)
#18     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:67:11)
#19     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#20     createLdapTransformer.<anonymous closure> (package:dartdap/src/client/ldap_transformer.dart:100:14)
#21     _HandlerEventSink.add (dart:async/stream_transformers.dart:230:17)
#22     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:115:24)
#23     _RootZone.runUnaryGuarded (dart:async/zone.dart:1778:10)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:381:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:312:7)
#26     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:798:19)
#27     _StreamController._add (dart:async/stream_controller.dart:663:7)
#28     _StreamController.add (dart:async/stream_controller.dart:618:5)
#29     _Socket._onData (dart:io-patch/socket_patch.dart:2904:41)
#30     _RootZone.runUnaryGuarded (dart:async/zone.dart:1778:10)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:381:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:312:7)
#33     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:798:19)
#34     _StreamController._add (dart:async/stream_controller.dart:663:7)
#35     _StreamController.add (dart:async/stream_controller.dart:618:5)
#36     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:2323:31)
#37     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1646:14)
#38     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#39     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

It seems to be caused by this line:
`loggerRecvLdap.finest('attribute: ${attrName.stringValue}=$valSet');`
in 
`#11     new SearchResultEntry (package:dartdap/src/protocol/search_result_entry.dart:48:73)`.

Could you please take a look and fix this?

Thanks again! 🙂

**Comment by wstrange** [comment]
Pushed  0.11.2 to workaround that error

**Comment by ibims270** [comment]
Version 0.11.2 is working perfectly.
Thank you so much!
